'use client';

import { BeanHead } from 'beanheads';
import { type AvatarId } from '@/lib/avatars';
import { type ReactElement } from 'react';

export const AVATAR_COMPONENTS: Record<AvatarId, () => ReactElement> = {
  'cool-dev': () => (
    <BeanHead
      accessory="tinyGlasses"
      body="chest"
      circleColor="blue"
      clothing="shirt"
      clothingColor="white"
      eyebrows="leftLowered"
      eyes="happy"
      facialHair="none"
      graphic="react"
      hair="short"
      hairColor="black"
      hat="none"
      lashes={false}
      mouth="grin"
      skinTone="light"
      mask
    />
  ),
  'happy-designer': () => (
    <BeanHead
      accessory="none"
      body="chest"
      circleColor="blue"
      clothing="vneck"
      clothingColor="black"
      eyebrows="raised"
      eyes="happy"
      facialHair="none"
      graphic="react"
      hair="bob"
      hairColor="brown"
      hat="none"
      lashes
      mouth="grin"
      skinTone="light"
      mask
    />
  ),
  'creative-artist': () => (
    <BeanHead
      accessory="roundGlasses"
      body="chest"
      circleColor="blue"
      clothing="shirt"
      clothingColor="blue"
      eyebrows="raised"
      eyes="happy"
      facialHair="none"
      graphic="react"
      hair="bun"
      hairColor="brown"
      hat="none"
      lashes
      mouth="grin"
      skinTone="light"
      mask
    />
  ),
  'tech-lead': () => (
    <BeanHead
      accessory="roundGlasses"
      body="chest"
      circleColor="blue"
      clothing="shirt"
      clothingColor="blue"
      eyebrows="serious"
      eyes="happy"
      facialHair="none"
      graphic="vue"
      hair="short"
      hairColor="black"
      hat="none"
      lashes={false}
      mouth="serious"
      skinTone="light"
      mask
    />
  ),
  'product-manager': () => (
    <BeanHead
      accessory="none"
      body="chest"
      circleColor="blue"
      clothing="dressShirt"
      clothingColor="blue"
      eyebrows="raised"
      eyes="simple"
      facialHair="none"
      graphic="vue"
      hair="short"
      hairColor="brown"
      hat="none"
      lashes
      mouth="grin"
      skinTone="light"
      mask
    />
  ),
  'qa-engineer': () => (
    <BeanHead
      accessory="roundGlasses"
      body="chest"
      circleColor="blue"
      clothing="shirt"
      clothingColor="blue"
      eyebrows="leftLowered"
      eyes="squint"
      facialHair="none"
      graphic="vue"
      hair="short"
      hairColor="black"
      hat="none"
      lashes={false}
      mouth="grin"
      skinTone="dark"
      mask
    />
  ),
  'devops-ninja': () => (
    <BeanHead
      accessory="shades"
      body="chest"
      circleColor="blue"
      clothing="tankTop"
      clothingColor="black"
      eyebrows="serious"
      eyes="squint"
      facialHair="none"
      graphic="vue"
      hair="short"
      hairColor="brown"
      hat="none"
      lashes={false}
      mouth="serious"
      skinTone="light"
      mask
    />
  ),
  'frontend-wizard': () => (
    <BeanHead
      accessory="tinyGlasses"
      body="chest"
      circleColor="blue"
      clothing="shirt"
      clothingColor="red"
      eyebrows="raised"
      eyes="happy"
      facialHair="none"
      graphic="react"
      hair="short"
      hairColor="brown"
      hat="none"
      lashes
      mouth="grin"
      skinTone="light"
      mask
    />
  ),
  'backend-guru': () => (
    <BeanHead
      accessory="roundGlasses"
      body="chest"
      circleColor="blue"
      clothing="shirt"
      clothingColor="green"
      eyebrows="serious"
      eyes="squint"
      facialHair="none"
      graphic="vue"
      hair="short"
      hairColor="brown"
      hat="none"
      lashes={false}
      mouth="serious"
      skinTone="light"
      mask
    />
  ),
  'mobile-ninja': () => (
    <BeanHead
      accessory="none"
      body="chest"
      circleColor="blue"
      clothing="dress"
      clothingColor="red"
      eyebrows="raised"
      eyes="happy"
      facialHair="none"
      graphic="react"
      hair="bob"
      hairColor="black"
      hat="none"
      lashes
      mouth="grin"
      skinTone="light"
      mask
    />
  )
}; 